include("operations/save_basic_features_instances.jl")
include("operations/save_features_instances.jl")
include("operations/save_single_features_instances.jl")
include("operations/serialize_instances.jl")
include("operations/generate_decompositions.jl")
include("operations/merge_decompositions.jl")
include("operations/check_sanity.jl")
