[load_in_db_instances_no_rawgo]
    indirs_rawgo = [""]
    indirs_matpowerm = ["data/MATPOWERM"]

[100_500]
    min_nv=100
    max_nv=500

    [100_500.0cholesky]
        extension_alg = "cholesky"
        preprocess_path = "configs/preprocess_0.json"

    [100_500.0minimum_degree]
        extension_alg = "minimum_degree"
        preprocess_path = "configs/preprocess_0.json"

    [100_500.merge_molzahn10]
        heuristic = ["molzahn"]
        heuristic_switch = [0]
        kwargs_path = "configs/merge.toml"
        kwargs_key = "default"


[100_2000]
    min_nv=100
    max_nv=2000

    [100_2000.0cholesky]
        extension_alg = "cholesky"
        preprocess_path = "configs/preprocess_0.json"

    [100_2000.0minimum_degree]
        extension_alg = "minimum_degree"
        preprocess_path = "configs/preprocess_0.json"

    [100_2000.merge_molzahn10]
        heuristic = ["molzahn"]
        heuristic_switch = [0]
        kwargs_path = "configs/merge.toml"
        kwargs_key = "default"

    [100_2000.0_01dist3cholesky]
        extension_alg = "cholesky"
        preprocess_path = "configs/preprocess_0_01dist3.json"
